<?php
/**
 * HealthMonitoringApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.09
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * HealthMonitoringApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HealthMonitoringApi
{

    /**
     * API Client
     *
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Swagger\Client\ApiClient $apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://localhost');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     *
     * @return HealthMonitoringApi
     */
    public function setApiClient(\Swagger\Client\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation getMonitoringRecords
     *
     * Monitor a Service Instance
     *
     * @param string $x_id_tenant_name Name of the identity domain for the MySQL Cloud Service account. (required)
     * @param string $identity_domain_id Name of the identity domain for the MySQL Cloud Service account. (required)
     * @param string $service_id Name of the Oracle MySQL Cloud Service instance. (required)
     * @param string $format Format of the health data. The only supported format for health data is &lt;code&gt;v1&lt;/code&gt;. (required)
     * @return \Swagger\Client\Model\MonitorResponse
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getMonitoringRecords($x_id_tenant_name, $identity_domain_id, $service_id, $format)
    {
        list($response) = $this->getMonitoringRecordsWithHttpInfo($x_id_tenant_name, $identity_domain_id, $service_id, $format);
        return $response;
    }

    /**
     * Operation getMonitoringRecordsWithHttpInfo
     *
     * Monitor a Service Instance
     *
     * @param string $x_id_tenant_name Name of the identity domain for the MySQL Cloud Service account. (required)
     * @param string $identity_domain_id Name of the identity domain for the MySQL Cloud Service account. (required)
     * @param string $service_id Name of the Oracle MySQL Cloud Service instance. (required)
     * @param string $format Format of the health data. The only supported format for health data is &lt;code&gt;v1&lt;/code&gt;. (required)
     * @return Array of \Swagger\Client\Model\MonitorResponse, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getMonitoringRecordsWithHttpInfo($x_id_tenant_name, $identity_domain_id, $service_id, $format)
    {
        // verify the required parameter 'x_id_tenant_name' is set
        if ($x_id_tenant_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $x_id_tenant_name when calling getMonitoringRecords');
        }
        // verify the required parameter 'identity_domain_id' is set
        if ($identity_domain_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $identity_domain_id when calling getMonitoringRecords');
        }
        // verify the required parameter 'service_id' is set
        if ($service_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $service_id when calling getMonitoringRecords');
        }
        // verify the required parameter 'format' is set
        if ($format === null) {
            throw new \InvalidArgumentException('Missing the required parameter $format when calling getMonitoringRecords');
        }
        // parse inputs
        $resourcePath = "/paas/api/v1.1/instancemgmt/{identityDomainId}/services/MySQLCS/instances/{serviceId}/healthcheck";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());

        // query params
        if ($format !== null) {
            $queryParams['format'] = $this->apiClient->getSerializer()->toQueryValue($format);
        }
        // header params
        if ($x_id_tenant_name !== null) {
            $headerParams['X-ID-TENANT-NAME'] = $this->apiClient->getSerializer()->toHeaderValue($x_id_tenant_name);
        }
        // path params
        if ($identity_domain_id !== null) {
            $resourcePath = str_replace(
                "{" . "identityDomainId" . "}",
                $this->apiClient->getSerializer()->toPathValue($identity_domain_id),
                $resourcePath
            );
        }
        // path params
        if ($service_id !== null) {
            $resourcePath = str_replace(
                "{" . "serviceId" . "}",
                $this->apiClient->getSerializer()->toPathValue($service_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-ID-TENANT-NAME');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-ID-TENANT-NAME'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\MonitorResponse',
                '/paas/api/v1.1/instancemgmt/{identityDomainId}/services/MySQLCS/instances/{serviceId}/healthcheck'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\MonitorResponse', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\MonitorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

}
