<?php
/**
 * BackupViewAllResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.18
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * BackupViewAllResponse Class Doc Comment
 *
 * @category    Class */
 // @description The response body contains information about all backups.
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BackupViewAllResponse implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'backup-view-all-response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'backups' => '\Swagger\Client\Model\BackupViewResponse[]',
        'backup_in_progress' => '\Swagger\Client\Model\BackupViewResponse[]',
        'last_failed_backup' => '\Swagger\Client\Model\BackupViewResponse[]'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'backups' => 'backups',
        'backup_in_progress' => 'backupInProgress',
        'last_failed_backup' => 'lastFailedBackup'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'backups' => 'setBackups',
        'backup_in_progress' => 'setBackupInProgress',
        'last_failed_backup' => 'setLastFailedBackup'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'backups' => 'getBackups',
        'backup_in_progress' => 'getBackupInProgress',
        'last_failed_backup' => 'getLastFailedBackup'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['backups'] = isset($data['backups']) ? $data['backups'] : null;
        $this->container['backup_in_progress'] = isset($data['backup_in_progress']) ? $data['backup_in_progress'] : null;
        $this->container['last_failed_backup'] = isset($data['last_failed_backup']) ? $data['last_failed_backup'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets backups
     * @return \Swagger\Client\Model\BackupViewResponse[]
     */
    public function getBackups()
    {
        return $this->container['backups'];
    }

    /**
     * Sets backups
     * @param \Swagger\Client\Model\BackupViewResponse[] $backups Groups all completed backups.
     * @return $this
     */
    public function setBackups($backups)
    {
        $this->container['backups'] = $backups;

        return $this;
    }

    /**
     * Gets backup_in_progress
     * @return \Swagger\Client\Model\BackupViewResponse[]
     */
    public function getBackupInProgress()
    {
        return $this->container['backup_in_progress'];
    }

    /**
     * Sets backup_in_progress
     * @param \Swagger\Client\Model\BackupViewResponse[] $backup_in_progress Groups the backups currently in progress, if any.
     * @return $this
     */
    public function setBackupInProgress($backup_in_progress)
    {
        $this->container['backup_in_progress'] = $backup_in_progress;

        return $this;
    }

    /**
     * Gets last_failed_backup
     * @return \Swagger\Client\Model\BackupViewResponse[]
     */
    public function getLastFailedBackup()
    {
        return $this->container['last_failed_backup'];
    }

    /**
     * Sets last_failed_backup
     * @param \Swagger\Client\Model\BackupViewResponse[] $last_failed_backup Groups the failed backups, if any.
     * @return $this
     */
    public function setLastFailedBackup($last_failed_backup)
    {
        $this->container['last_failed_backup'] = $last_failed_backup;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


