<?php
/**
 * RollbackResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.06
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * RollbackResult Class Doc Comment
 *
 * @category    Class */
 // @description Groups information about the results of the rollback operation. This attribute displays only when a rollback of the patch had been performed.
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RollbackResult implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'rollback-result';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'rollback_id' => 'int',
        'start_date' => 'string',
        'end_date' => 'string',
        'patching_status' => 'string',
        'result_message' => 'string',
        'additional_note' => 'string',
        'applied_by' => 'string',
        'job_id' => 'string',
        'complete_log' => 'string',
        'progress_messages' => 'string[]'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'rollback_id' => 'rollbackId',
        'start_date' => 'startDate',
        'end_date' => 'endDate',
        'patching_status' => 'patchingStatus',
        'result_message' => 'resultMessage',
        'additional_note' => 'additionalNote',
        'applied_by' => 'appliedBy',
        'job_id' => 'jobId',
        'complete_log' => 'completeLog',
        'progress_messages' => 'progressMessages'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'rollback_id' => 'setRollbackId',
        'start_date' => 'setStartDate',
        'end_date' => 'setEndDate',
        'patching_status' => 'setPatchingStatus',
        'result_message' => 'setResultMessage',
        'additional_note' => 'setAdditionalNote',
        'applied_by' => 'setAppliedBy',
        'job_id' => 'setJobId',
        'complete_log' => 'setCompleteLog',
        'progress_messages' => 'setProgressMessages'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'rollback_id' => 'getRollbackId',
        'start_date' => 'getStartDate',
        'end_date' => 'getEndDate',
        'patching_status' => 'getPatchingStatus',
        'result_message' => 'getResultMessage',
        'additional_note' => 'getAdditionalNote',
        'applied_by' => 'getAppliedBy',
        'job_id' => 'getJobId',
        'complete_log' => 'getCompleteLog',
        'progress_messages' => 'getProgressMessages'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['rollback_id'] = isset($data['rollback_id']) ? $data['rollback_id'] : null;
        $this->container['start_date'] = isset($data['start_date']) ? $data['start_date'] : null;
        $this->container['end_date'] = isset($data['end_date']) ? $data['end_date'] : null;
        $this->container['patching_status'] = isset($data['patching_status']) ? $data['patching_status'] : null;
        $this->container['result_message'] = isset($data['result_message']) ? $data['result_message'] : null;
        $this->container['additional_note'] = isset($data['additional_note']) ? $data['additional_note'] : null;
        $this->container['applied_by'] = isset($data['applied_by']) ? $data['applied_by'] : null;
        $this->container['job_id'] = isset($data['job_id']) ? $data['job_id'] : null;
        $this->container['complete_log'] = isset($data['complete_log']) ? $data['complete_log'] : null;
        $this->container['progress_messages'] = isset($data['progress_messages']) ? $data['progress_messages'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets rollback_id
     * @return int
     */
    public function getRollbackId()
    {
        return $this->container['rollback_id'];
    }

    /**
     * Sets rollback_id
     * @param int $rollback_id ID of the rollback operation.
     * @return $this
     */
    public function setRollbackId($rollback_id)
    {
        $this->container['rollback_id'] = $rollback_id;

        return $this;
    }

    /**
     * Gets start_date
     * @return string
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     * @param string $start_date Date and time that the rollback operation started.
     * @return $this
     */
    public function setStartDate($start_date)
    {
        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets end_date
     * @return string
     */
    public function getEndDate()
    {
        return $this->container['end_date'];
    }

    /**
     * Sets end_date
     * @param string $end_date Date the rollback operation ended.
     * @return $this
     */
    public function setEndDate($end_date)
    {
        $this->container['end_date'] = $end_date;

        return $this;
    }

    /**
     * Gets patching_status
     * @return string
     */
    public function getPatchingStatus()
    {
        return $this->container['patching_status'];
    }

    /**
     * Sets patching_status
     * @param string $patching_status Status of the rollback operation. For example, <code>COMPLETED_ROLLBACK</code>.
     * @return $this
     */
    public function setPatchingStatus($patching_status)
    {
        $this->container['patching_status'] = $patching_status;

        return $this;
    }

    /**
     * Gets result_message
     * @return string
     */
    public function getResultMessage()
    {
        return $this->container['result_message'];
    }

    /**
     * Sets result_message
     * @param string $result_message System message that describes the rollback operation.
     * @return $this
     */
    public function setResultMessage($result_message)
    {
        $this->container['result_message'] = $result_message;

        return $this;
    }

    /**
     * Gets additional_note
     * @return string
     */
    public function getAdditionalNote()
    {
        return $this->container['additional_note'];
    }

    /**
     * Sets additional_note
     * @param string $additional_note Free-form text to provide additional information about the rollback.
     * @return $this
     */
    public function setAdditionalNote($additional_note)
    {
        $this->container['additional_note'] = $additional_note;

        return $this;
    }

    /**
     * Gets applied_by
     * @return string
     */
    public function getAppliedBy()
    {
        return $this->container['applied_by'];
    }

    /**
     * Sets applied_by
     * @param string $applied_by Name of the user that performed the rollback.
     * @return $this
     */
    public function setAppliedBy($applied_by)
    {
        $this->container['applied_by'] = $applied_by;

        return $this;
    }

    /**
     * Gets job_id
     * @return string
     */
    public function getJobId()
    {
        return $this->container['job_id'];
    }

    /**
     * Sets job_id
     * @param string $job_id Job ID for the rollback operation.
     * @return $this
     */
    public function setJobId($job_id)
    {
        $this->container['job_id'] = $job_id;

        return $this;
    }

    /**
     * Gets complete_log
     * @return string
     */
    public function getCompleteLog()
    {
        return $this->container['complete_log'];
    }

    /**
     * Sets complete_log
     * @param string $complete_log System messages that track the rollback operations.
     * @return $this
     */
    public function setCompleteLog($complete_log)
    {
        $this->container['complete_log'] = $complete_log;

        return $this;
    }

    /**
     * Gets progress_messages
     * @return string[]
     */
    public function getProgressMessages()
    {
        return $this->container['progress_messages'];
    }

    /**
     * Sets progress_messages
     * @param string[] $progress_messages List of progress messages for the rollback.
     * @return $this
     */
    public function setProgressMessages($progress_messages)
    {
        $this->container['progress_messages'] = $progress_messages;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


