<?php
/**
 * AppliedPatchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.06
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AppliedPatchTest Class Doc Comment
 *
 * @category    Class */
// * @description Information about an applied patch.
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AppliedPatchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AppliedPatch"
     */
    public function testAppliedPatch()
    {

    }

    /**
     * Test attribute "backup_status"
     */
    public function testPropertyBackupStatus()
    {

    }

    /**
     * Test attribute "additional_note"
     */
    public function testPropertyAdditionalNote()
    {

    }

    /**
     * Test attribute "applied_by"
     */
    public function testPropertyAppliedBy()
    {

    }

    /**
     * Test attribute "applied_date"
     */
    public function testPropertyAppliedDate()
    {

    }

    /**
     * Test attribute "total_time"
     */
    public function testPropertyTotalTime()
    {

    }

    /**
     * Test attribute "patch_id"
     */
    public function testPropertyPatchId()
    {

    }

    /**
     * Test attribute "patch_description"
     */
    public function testPropertyPatchDescription()
    {

    }

    /**
     * Test attribute "patch_release_url"
     */
    public function testPropertyPatchReleaseUrl()
    {

    }

    /**
     * Test attribute "release_date"
     */
    public function testPropertyReleaseDate()
    {

    }

    /**
     * Test attribute "result_message"
     */
    public function testPropertyResultMessage()
    {

    }

    /**
     * Test attribute "last_status"
     */
    public function testPropertyLastStatus()
    {

    }

    /**
     * Test attribute "last_status_message"
     */
    public function testPropertyLastStatusMessage()
    {

    }

    /**
     * Test attribute "component_patches"
     */
    public function testPropertyComponentPatches()
    {

    }

    /**
     * Test attribute "patch_components"
     */
    public function testPropertyPatchComponents()
    {

    }

    /**
     * Test attribute "patch_type"
     */
    public function testPropertyPatchType()
    {

    }

    /**
     * Test attribute "patch_category"
     */
    public function testPropertyPatchCategory()
    {

    }

    /**
     * Test attribute "patch_severity"
     */
    public function testPropertyPatchSeverity()
    {

    }

    /**
     * Test attribute "job_id"
     */
    public function testPropertyJobId()
    {

    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {

    }

    /**
     * Test attribute "to_version"
     */
    public function testPropertyToVersion()
    {

    }

    /**
     * Test attribute "backup_id"
     */
    public function testPropertyBackupId()
    {

    }

    /**
     * Test attribute "in_progress"
     */
    public function testPropertyInProgress()
    {

    }

    /**
     * Test attribute "operation_type"
     */
    public function testPropertyOperationType()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "patching_result"
     */
    public function testPropertyPatchingResult()
    {

    }

    /**
     * Test attribute "rollback_result"
     */
    public function testPropertyRollbackResult()
    {

    }

    /**
     * Test attribute "rollback_id"
     */
    public function testPropertyRollbackId()
    {

    }

    /**
     * Test attribute "rollback_version"
     */
    public function testPropertyRollbackVersion()
    {

    }

    /**
     * Test attribute "current_patch_level"
     */
    public function testPropertyCurrentPatchLevel()
    {

    }

    /**
     * Test attribute "progress_messages"
     */
    public function testPropertyProgressMessages()
    {

    }

}
