<?php
/**
 * AvailablePatchesResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.09
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AvailablePatchesResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description The response body contains information about the available patches.
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AvailablePatchesResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AvailablePatchesResponse"
     */
    public function testAvailablePatchesResponse()
    {

    }

    /**
     * Test attribute "available_patch_gui_metadata"
     */
    public function testPropertyAvailablePatchGuiMetadata()
    {

    }

    /**
     * Test attribute "patch_id"
     */
    public function testPropertyPatchId()
    {

    }

    /**
     * Test attribute "patch_number"
     */
    public function testPropertyPatchNumber()
    {

    }

    /**
     * Test attribute "patch_category"
     */
    public function testPropertyPatchCategory()
    {

    }

    /**
     * Test attribute "patch_severity"
     */
    public function testPropertyPatchSeverity()
    {

    }

    /**
     * Test attribute "includes_config_upgrade"
     */
    public function testPropertyIncludesConfigUpgrade()
    {

    }

    /**
     * Test attribute "patch_description"
     */
    public function testPropertyPatchDescription()
    {

    }

    /**
     * Test attribute "patch_release_url"
     */
    public function testPropertyPatchReleaseUrl()
    {

    }

    /**
     * Test attribute "service_type"
     */
    public function testPropertyServiceType()
    {

    }

    /**
     * Test attribute "service_version"
     */
    public function testPropertyServiceVersion()
    {

    }

    /**
     * Test attribute "release_date"
     */
    public function testPropertyReleaseDate()
    {

    }

    /**
     * Test attribute "entry_date"
     */
    public function testPropertyEntryDate()
    {

    }

    /**
     * Test attribute "entry_user_id"
     */
    public function testPropertyEntryUserId()
    {

    }

    /**
     * Test attribute "component_patches"
     */
    public function testPropertyComponentPatches()
    {

    }

    /**
     * Test attribute "patch_components"
     */
    public function testPropertyPatchComponents()
    {

    }

    /**
     * Test attribute "patch_type"
     */
    public function testPropertyPatchType()
    {

    }

    /**
     * Test attribute "requires_restart"
     */
    public function testPropertyRequiresRestart()
    {

    }

    /**
     * Test attribute "service_type_versions"
     */
    public function testPropertyServiceTypeVersions()
    {

    }

    /**
     * Test attribute "is_deleted"
     */
    public function testPropertyIsDeleted()
    {

    }

    /**
     * Test attribute "is_customer_visible"
     */
    public function testPropertyIsCustomerVisible()
    {

    }

    /**
     * Test attribute "is_auto_apply"
     */
    public function testPropertyIsAutoApply()
    {

    }

    /**
     * Test attribute "induce_down_time"
     */
    public function testPropertyInduceDownTime()
    {

    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {

    }

    /**
     * Test attribute "meta_version"
     */
    public function testPropertyMetaVersion()
    {

    }

    /**
     * Test attribute "supported_strategy"
     */
    public function testPropertySupportedStrategy()
    {

    }

    /**
     * Test attribute "release_version"
     */
    public function testPropertyReleaseVersion()
    {

    }

    /**
     * Test attribute "patch_custom_actions"
     */
    public function testPropertyPatchCustomActions()
    {

    }

}
