<?php
/**
 * BackupconfigResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.06
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BackupconfigResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description The response body includes information about the backup configuration. If an update request was initiated and successfully completed, the response body shows the updated configuration.
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BackupconfigResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "BackupconfigResponse"
     */
    public function testBackupconfigResponse()
    {

    }

    /**
     * Test attribute "default_retention"
     */
    public function testPropertyDefaultRetention()
    {

    }

    /**
     * Test attribute "full_backup_schedule"
     */
    public function testPropertyFullBackupSchedule()
    {

    }

    /**
     * Test attribute "incremental_backup_schedule"
     */
    public function testPropertyIncrementalBackupSchedule()
    {

    }

    /**
     * Test attribute "scheduled_backups"
     */
    public function testPropertyScheduledBackups()
    {

    }

    /**
     * Test attribute "extended_restore_types"
     */
    public function testPropertyExtendedRestoreTypes()
    {

    }

    /**
     * Test attribute "last_backup_date"
     */
    public function testPropertyLastBackupDate()
    {

    }

    /**
     * Test attribute "next_full_backup_date"
     */
    public function testPropertyNextFullBackupDate()
    {

    }

    /**
     * Test attribute "next_incremental_backup_date"
     */
    public function testPropertyNextIncrementalBackupDate()
    {

    }

    /**
     * Test attribute "last_successful_cleanup_date"
     */
    public function testPropertyLastSuccessfulCleanupDate()
    {

    }

    /**
     * Test attribute "backup_destination"
     */
    public function testPropertyBackupDestination()
    {

    }

    /**
     * Test attribute "cloud_storage_container"
     */
    public function testPropertyCloudStorageContainer()
    {

    }

    /**
     * Test attribute "cloud_storage_user"
     */
    public function testPropertyCloudStorageUser()
    {

    }

    /**
     * Test attribute "total_cloud_storage_container_used"
     */
    public function testPropertyTotalCloudStorageContainerUsed()
    {

    }

    /**
     * Test attribute "total_cloud_storage_container_used_in_bytes"
     */
    public function testPropertyTotalCloudStorageContainerUsedInBytes()
    {

    }

    /**
     * Test attribute "total_backup_volume_used"
     */
    public function testPropertyTotalBackupVolumeUsed()
    {

    }

    /**
     * Test attribute "total_backup_volume_used_in_bytes"
     */
    public function testPropertyTotalBackupVolumeUsedInBytes()
    {

    }

    /**
     * Test attribute "percent_backup_volume_used"
     */
    public function testPropertyPercentBackupVolumeUsed()
    {

    }

}
