<?php
/**
 * CreateInstanceServiceParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.09
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateInstanceServiceParametersTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateInstanceServiceParameters
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateInstanceServiceParametersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CreateInstanceServiceParameters"
     */
    public function testCreateInstanceServiceParameters()
    {

    }

    /**
     * Test attribute "service_name"
     */
    public function testPropertyServiceName()
    {

    }

    /**
     * Test attribute "service_description"
     */
    public function testPropertyServiceDescription()
    {

    }

    /**
     * Test attribute "metering_frequency"
     */
    public function testPropertyMeteringFrequency()
    {

    }

    /**
     * Test attribute "backup_destination"
     */
    public function testPropertyBackupDestination()
    {

    }

    /**
     * Test attribute "cloud_storage_container"
     */
    public function testPropertyCloudStorageContainer()
    {

    }

    /**
     * Test attribute "cloud_storage_user"
     */
    public function testPropertyCloudStorageUser()
    {

    }

    /**
     * Test attribute "cloud_storage_password"
     */
    public function testPropertyCloudStoragePassword()
    {

    }

    /**
     * Test attribute "cloud_storage_container_auto_generate"
     */
    public function testPropertyCloudStorageContainerAutoGenerate()
    {

    }

    /**
     * Test attribute "vm_user"
     */
    public function testPropertyVmUser()
    {

    }

    /**
     * Test attribute "vm_public_key_text"
     */
    public function testPropertyVmPublicKeyText()
    {

    }

    /**
     * Test attribute "no_rollback"
     */
    public function testPropertyNoRollback()
    {

    }

}
