<?php
/**
 * ServiceCreateInstanceParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.18
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ServiceCreateInstanceParametersTest Class Doc Comment
 *
 * @category    Class */
// * @description ServiceCreateInstanceParameters
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServiceCreateInstanceParametersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ServiceCreateInstanceParameters"
     */
    public function testServiceCreateInstanceParameters()
    {

    }

    /**
     * Test attribute "shape"
     */
    public function testPropertyShape()
    {

    }

    /**
     * Test attribute "mysql_user_name"
     */
    public function testPropertyMysqlUserName()
    {

    }

    /**
     * Test attribute "mysql_user_password"
     */
    public function testPropertyMysqlUserPassword()
    {

    }

    /**
     * Test attribute "mysql_port"
     */
    public function testPropertyMysqlPort()
    {

    }

    /**
     * Test attribute "mysql_em_port"
     */
    public function testPropertyMysqlEmPort()
    {

    }

    /**
     * Test attribute "db_storage"
     */
    public function testPropertyDbStorage()
    {

    }

    /**
     * Test attribute "db_name"
     */
    public function testPropertyDbName()
    {

    }

    /**
     * Test attribute "mysql_charset"
     */
    public function testPropertyMysqlCharset()
    {

    }

    /**
     * Test attribute "mysql_collation"
     */
    public function testPropertyMysqlCollation()
    {

    }

    /**
     * Test attribute "enterprise_monitor"
     */
    public function testPropertyEnterpriseMonitor()
    {

    }

    /**
     * Test attribute "enterprise_monitor_manager_user"
     */
    public function testPropertyEnterpriseMonitorManagerUser()
    {

    }

    /**
     * Test attribute "enterprise_monitor_manager_password"
     */
    public function testPropertyEnterpriseMonitorManagerPassword()
    {

    }

    /**
     * Test attribute "enterprise_monitor_agent_user"
     */
    public function testPropertyEnterpriseMonitorAgentUser()
    {

    }

    /**
     * Test attribute "enterprise_monitor_agent_password"
     */
    public function testPropertyEnterpriseMonitorAgentPassword()
    {

    }

}
