<?php
/**
 * ServiceViewComponentsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.18
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ServiceViewComponentsTest Class Doc Comment
 *
 * @category    Class */
// * @description ServiceViewComponents
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServiceViewComponentsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ServiceViewComponents"
     */
    public function testServiceViewComponents()
    {

    }

    /**
     * Test attribute "service_id"
     */
    public function testPropertyServiceId()
    {

    }

    /**
     * Test attribute "component_id"
     */
    public function testPropertyComponentId()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {

    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {

    }

    /**
     * Test attribute "instance_name"
     */
    public function testPropertyInstanceName()
    {

    }

    /**
     * Test attribute "instance_role"
     */
    public function testPropertyInstanceRole()
    {

    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {

    }

    /**
     * Test attribute "vm_instances"
     */
    public function testPropertyVmInstances()
    {

    }

    /**
     * Test attribute "admin_host_name"
     */
    public function testPropertyAdminHostName()
    {

    }

    /**
     * Test attribute "storage_volumes"
     */
    public function testPropertyStorageVolumes()
    {

    }

}
