<?php
/**
 * ViewPrecheckResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.09
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ViewPrecheckResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description The response body includes information about the patch precheck. When viewing all patching prechecks, the response body includes information about all patch prechecks executed on this service instance.
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ViewPrecheckResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ViewPrecheckResponse"
     */
    public function testViewPrecheckResponse()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "job_id"
     */
    public function testPropertyJobId()
    {

    }

    /**
     * Test attribute "patch_id"
     */
    public function testPropertyPatchId()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {

    }

    /**
     * Test attribute "performed_by"
     */
    public function testPropertyPerformedBy()
    {

    }

    /**
     * Test attribute "in_progress"
     */
    public function testPropertyInProgress()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "href"
     */
    public function testPropertyHref()
    {

    }

    /**
     * Test attribute "pre_check_messages"
     */
    public function testPropertyPreCheckMessages()
    {

    }

    /**
     * Test attribute "result_message"
     */
    public function testPropertyResultMessage()
    {

    }

}
