<?php
/**
 * ViewVmInstanceNodesArrayItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.06
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ViewVmInstanceNodesArrayItemTest Class Doc Comment
 *
 * @category    Class */
// * @description ViewVmInstanceNodesArrayItem
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ViewVmInstanceNodesArrayItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ViewVmInstanceNodesArrayItem"
     */
    public function testViewVmInstanceNodesArrayItem()
    {

    }

    /**
     * Test attribute "vm_id"
     */
    public function testPropertyVmId()
    {

    }

    /**
     * Test attribute "hostname"
     */
    public function testPropertyHostname()
    {

    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {

    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {

    }

    /**
     * Test attribute "public_ip_address"
     */
    public function testPropertyPublicIpAddress()
    {

    }

    /**
     * Test attribute "usage_type"
     */
    public function testPropertyUsageType()
    {

    }

    /**
     * Test attribute "role"
     */
    public function testPropertyRole()
    {

    }

    /**
     * Test attribute "component_type"
     */
    public function testPropertyComponentType()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "shape_id"
     */
    public function testPropertyShapeId()
    {

    }

    /**
     * Test attribute "total_storage"
     */
    public function testPropertyTotalStorage()
    {

    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {

    }

    /**
     * Test attribute "is_admin_node"
     */
    public function testPropertyIsAdminNode()
    {

    }

    /**
     * Test attribute "servers"
     */
    public function testPropertyServers()
    {

    }

    /**
     * Test attribute "storage_volumes"
     */
    public function testPropertyStorageVolumes()
    {

    }

    /**
     * Test attribute "vm_state_display_name"
     */
    public function testPropertyVmStateDisplayName()
    {

    }

}
