<?php
/**
 * ViewInstanceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.18
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ViewInstanceTest Class Doc Comment
 *
 * @category    Class */
// * @description ViewInstance
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ViewInstanceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ViewInstance"
     */
    public function testViewInstance()
    {

    }

    /**
     * Test attribute "service_id"
     */
    public function testPropertyServiceId()
    {

    }

    /**
     * Test attribute "service_name"
     */
    public function testPropertyServiceName()
    {

    }

    /**
     * Test attribute "service_type"
     */
    public function testPropertyServiceType()
    {

    }

    /**
     * Test attribute "domain_name"
     */
    public function testPropertyDomainName()
    {

    }

    /**
     * Test attribute "service_version"
     */
    public function testPropertyServiceVersion()
    {

    }

    /**
     * Test attribute "release_version"
     */
    public function testPropertyReleaseVersion()
    {

    }

    /**
     * Test attribute "meta_version"
     */
    public function testPropertyMetaVersion()
    {

    }

    /**
     * Test attribute "service_level"
     */
    public function testPropertyServiceLevel()
    {

    }

    /**
     * Test attribute "subscription"
     */
    public function testPropertySubscription()
    {

    }

    /**
     * Test attribute "metering_frequency"
     */
    public function testPropertyMeteringFrequency()
    {

    }

    /**
     * Test attribute "edition"
     */
    public function testPropertyEdition()
    {

    }

    /**
     * Test attribute "cloud_storage_container"
     */
    public function testPropertyCloudStorageContainer()
    {

    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {

    }

    /**
     * Test attribute "components"
     */
    public function testPropertyComponents()
    {

    }

    /**
     * Test attribute "activity_logs"
     */
    public function testPropertyActivityLogs()
    {

    }

    /**
     * Test attribute "service_level_display_name"
     */
    public function testPropertyServiceLevelDisplayName()
    {

    }

    /**
     * Test attribute "edition_display_name"
     */
    public function testPropertyEditionDisplayName()
    {

    }

    /**
     * Test attribute "metering_frequency_display_name"
     */
    public function testPropertyMeteringFrequencyDisplayName()
    {

    }

    /**
     * Test attribute "data_volume_size"
     */
    public function testPropertyDataVolumeSize()
    {

    }

    /**
     * Test attribute "mysql_port"
     */
    public function testPropertyMysqlPort()
    {

    }

    /**
     * Test attribute "backup_destination"
     */
    public function testPropertyBackupDestination()
    {

    }

    /**
     * Test attribute "cloud_storage_container"
     */
    public function testPropertyCloudStorageContainer()
    {

    }

    /**
     * Test attribute "local_backup_volume_mount"
     */
    public function testPropertyLocalBackupVolumeMount()
    {

    }

    /**
     * Test attribute "local_backup_volume_size"
     */
    public function testPropertyLocalBackupVolumeSize()
    {

    }

    /**
     * Test attribute "total_shared_storage"
     */
    public function testPropertyTotalSharedStorage()
    {

    }

    /**
     * Test attribute "service_state_display_name"
     */
    public function testPropertyServiceStateDisplayName()
    {

    }

    /**
     * Test attribute "compute_site_name"
     */
    public function testPropertyComputeSiteName()
    {

    }

    /**
     * Test attribute "patching"
     */
    public function testPropertyPatching()
    {

    }

}
