<?php
/**
 * ViewBackupTagTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.06
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ViewBackupTagTest Class Doc Comment
 *
 * @category    Class */
// * @description ViewBackupTag
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ViewBackupTagTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ViewBackupTag"
     */
    public function testViewBackupTag()
    {

    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {

    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {

    }

    /**
     * Test attribute "start_lsn"
     */
    public function testPropertyStartLsn()
    {

    }

    /**
     * Test attribute "end_lsn"
     */
    public function testPropertyEndLsn()
    {

    }

    /**
     * Test attribute "last_bin_log"
     */
    public function testPropertyLastBinLog()
    {

    }

    /**
     * Test attribute "last_bin_log_pos"
     */
    public function testPropertyLastBinLogPos()
    {

    }

    /**
     * Test attribute "triggered_by"
     */
    public function testPropertyTriggeredBy()
    {

    }

}
