<?php
/**
 * BackupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.09
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * BackupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BackupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for deleteBackup
     *
     * Delete a Backup (Asynchronous).
     *
     */
    public function testDeleteBackup()
    {

    }

    /**
     * Test case for getAllBackups
     *
     * View All Backups.
     *
     */
    public function testGetAllBackups()
    {

    }

    /**
     * Test case for getAllDeletedBackups
     *
     * View All Deleted Backups.
     *
     */
    public function testGetAllDeletedBackups()
    {

    }

    /**
     * Test case for getBackup
     *
     * View a Backup.
     *
     */
    public function testGetBackup()
    {

    }

    /**
     * Test case for getBackupConfiguration
     *
     * View the Backup Configuration.
     *
     */
    public function testGetBackupConfiguration()
    {

    }

    /**
     * Test case for getDeletedBackup
     *
     * View a Deleted Backup.
     *
     */
    public function testGetDeletedBackup()
    {

    }

    /**
     * Test case for getRestoreBackupOperations
     *
     * View All Restoration Operations.
     *
     */
    public function testGetRestoreBackupOperations()
    {

    }

    /**
     * Test case for getRestoreBackupStatus
     *
     * View the Status of a Restoration Operation.
     *
     */
    public function testGetRestoreBackupStatus()
    {

    }

    /**
     * Test case for restoreBackup
     *
     * Restore a Service Instance from Backup.
     *
     */
    public function testRestoreBackup()
    {

    }

    /**
     * Test case for startBackup
     *
     * Initiate an On-demand Backup.
     *
     */
    public function testStartBackup()
    {

    }

    /**
     * Test case for updateBackupConfiguration
     *
     * Update the Backup Configuration.
     *
     */
    public function testUpdateBackupConfiguration()
    {

    }

}
