<?php
/**
 * ServiceInstancesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API for MySQL Cloud Service
 *
 * Use the REST API to manage MySQL Cloud Service instances
 *
 * OpenAPI spec version: 2017.01.09
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ServiceInstancesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServiceInstancesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addInstance
     *
     * Create an Oracle MySQL Cloud Service Instance.
     *
     */
    public function testAddInstance()
    {

    }

    /**
     * Test case for addInstanceStorage
     *
     * Add storage to a MySQL Cloud Service instance.
     *
     */
    public function testAddInstanceStorage()
    {

    }

    /**
     * Test case for deleteInstance
     *
     * Delete a Service Instance.
     *
     */
    public function testDeleteInstance()
    {

    }

    /**
     * Test case for getAllInstances
     *
     * View All Service Instances.
     *
     */
    public function testGetAllInstances()
    {

    }

    /**
     * Test case for getInstance
     *
     * View a Service Instance.
     *
     */
    public function testGetInstance()
    {

    }

    /**
     * Test case for getJobStatus
     *
     * View the Activity Log of a Job.
     *
     */
    public function testGetJobStatus()
    {

    }

    /**
     * Test case for scaleInstance
     *
     * Scale a MySQL Cloud Service instance.
     *
     */
    public function testScaleInstance()
    {

    }

    /**
     * Test case for updateInstanceStatus
     *
     * Start, Stop, or Restart a Service Instance.
     *
     */
    public function testUpdateInstanceStatus()
    {

    }

}
